name: Compile changelogs

on:
  schedule:
    - cron: "2 23 * * *"
  workflow_dispatch:

jobs:
  compile:
    name: "Compile changelogs"
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: "Check for ACTION_ENABLER secret and pass true to output if it exists to be checked by later steps"
        id: value_holder
        env:
          ENABLER_SECRET: ${{ secrets.ACTION_ENABLER }}
        run: |
          unset SECRET_EXISTS
          if [ -n "$ENABLER_SECRET" ]; then SECRET_EXISTS=true ; fi
          echo "ACTIONS_ENABLED=$SECRET_EXISTS" >> $GITHUB_OUTPUT

      - name: "Setup python"
        if: steps.value_holder.outputs.ACTIONS_ENABLED
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: "Install deps"
        if: steps.value_holder.outputs.ACTIONS_ENABLED
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyyaml
          sudo apt-get install  dos2unix

      - name: "Checkout"
        if: steps.value_holder.outputs.ACTIONS_ENABLED
        uses: actions/checkout@v4
        with:
          fetch-depth: 25
          persist-credentials: false

      - name: "Compile"
        if: steps.value_holder.outputs.ACTIONS_ENABLED
        run: |
          python tools/ss13_genchangelog.py html/changelogs

      - name: Commit
        if: steps.value_holder.outputs.ACTIONS_ENABLED
        run: |
          git config --local user.name "skyynet-se"
          git config --local user.email "134967240+skyynet-se@users.noreply.github.com"
          git pull origin main
          git add html/changelogs
          git commit -m "Effigy automatic changelog compile [ci skip]" -a || true
      - name: "Push"
        if: steps.value_holder.outputs.ACTIONS_ENABLED
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.SKYYNET_PAT || secrets.GITHUB_TOKEN }}
